### ISSUE TITLE
start with conda

### ISSUE THREAD

**Issue by Balays** [abremges/CAMITAX#19]
Hello
Can you please provide some help on how to run camitax with conda? How to config the nextflow config file to do this?
Neither Docker nor singularity is an option for me at the moment. 
I have created a conda env, activated it, installed the requirements, cloned the repo and I have all the dbs and nextflow as well.
Thanks. Cheers, Balazs.

**Comment by abremges** [comment]
Thank you for your interest, @Balays – the README is indeed a bit outdated, sorry for that.

But it should be as simple as setting `docker.enabled` to `false` in the configuration YAML.
Current line 8 in: https://github.com/CAMI-challenge/CAMITAX/blob/master/nextflow.config

Untested, though. I or @AlphaSquad will try to find the time to actually look into it these days.
I'd appreciate if you leave your feedback here, in case it works (or doesn't work). Thanks!

**Comment by abremges** [comment]
I updated the configuration file, introducing [profiles](https://www.nextflow.io/docs/latest/config.html?config-profiles#config-profiles). If you do not specify any profile (i.e. `docker` or `singularity`), CAMITAX will (attempt to) run natively. In other words, `nextflow run CAMI-challenge/CAMITAX --db /path/to/db/folder --i input --x fasta` should now do the trick.

**Please note that all dependencies need to be installed manually, which is a hassle (e.g. due to conflicting Python dependencies).** I am looking into ways to further streamline this with help from @AlphaSquad. Please let me know if this solution works for you, closing here.
